steps:
  # Step 1: Install dependencies (optional – mostly for testing or linting)
  - name: 'python:3.12'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt

  # Step 2: Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'app', 'deploy', '--quiet']
  options:
    logging: CLOUD_LOGGING_ONLY
# Optional: Specify a timeout (default is 10 minutes)
timeout: '900s'
